# === git ===
alias ga='git add'
alias gc='git commit'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'
alias gt='git tag'
alias gst='git stash'
# gl/gp are functions in gh-account.sh: they retry across gh accounts on an auth error
alias gr='git remote'
alias grv='git remote -v'
alias gb='git branch'
alias gwt='git worktree'
alias gwtr='git worktree remove'
alias gsw='git switch'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gm='git merge'
alias grb='git rebase'
alias glog='git log --oneline'

# === tools ===
alias l='ls -lhA'
alias path='echo "$PATH" | tr ":" "\n"'
alias pt='pytest'
alias pip='uv pip'
