#!/bin/sh
# git commit hook that checks for spelling errors in commit messages.
# Install this hook by placing it in the default location for git hooks (.git/hooks) or
# if a custom path was set, place it at `git config core.hooksPath`.

# Adapted from https://reddit.com/r/bash/comments/49sflp/spellcheck_git_commit_hook.
if ! command -v aspell &> /dev/null; then
  printf "%s\n" "[commit-msg hook] Warning: 'aspell' not installed. Unable to spell check commit message."
else
  mapfile -t wordList < <(grep -v "^  " "$1" | aspell list)
fi

if (( "${#wordList[@]}" > 0 )); then
  printf "%s\n" "[commit-msg hook] Possible spelling errors found in commit message:" "${wordList[@]}"
fi

# Check if running inside a terminal where the user can be prompted to handle
# possible spelling errors. See https://stackoverflow.com/a/911213.
if [ -t 1 ]; then
  # Adapted from https://stackoverflow.com/a/10015707.
  exec < /dev/tty

  while true; do
    read -r "YorN?[commit-msg hook] Press n to abort and change the commit message or y to proceed anyway?"$'\n'
    if [ "$YorN" = "" ]; then YorN='y'; fi # interpret enter as y
    case $YorN in
        [Yy] ) echo Proceeding...; break;;
        [Nn] ) echo Exiting...; exit 1;;
        * ) echo "Enter y for yes or n for no.";;
    esac
  done
fi