#!/bin/bash

# used with macOS Automator Folder Actions when screenshots are added to ~/Desktop
# remember to pass inputs as arguments!
# brew install pngquant zopfli

# view syslog stream with
# log stream --info --debug --predicate 'process == "syslog"'

# if folder action doesn't appear to trigger after setup, try toggling
# "Enable Folder ACtions" in "Folder Actions Setup.app" or add one of the
# default and see if it runs

for f in "$@"
do
  /usr/local/bin/pngquant 32 --skip-if-larger --ext .png --force "$f"
  # https://apple.stackexchange.com/a/385167
  syslog -s -l i "pngquant finished $f"

  /usr/local/bin/zopflipng -y "$f" "$f"
  syslog -s -l i "zopflipng finished $f"

  # https://stackoverflow.com/a/50703736
  osascript -e 'on run {f, c}' -e 'tell app "Finder" to set comment of (POSIX file f as alias) to c' -e end file://"$f" "Compressed with pngquant and zopflipng by Automator Folder Action \"Compress Screenshots\"."
  syslog -s -l i "added compression comment to $f"

  mv "$f" ~/Downloads/"${f##*/}"
  syslog -s -l i "moved $f to Downloads"
done